import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import MainContext from "@/components/MainContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Ecobazar",
  description: "Generated by create next app",
};

export default function RootLayout({ children}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <MainContext>
        <Header/>
        {children}
        <Footer/>
        </MainContext>
      </body>
    </html>
  );
}
